# Generated by Django 4.0.3 on 2022-05-01 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manageCake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
